apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-init-deployment
  namespace: 1-3
spec:
  selector:
    matchLabels:
      app: nginx-init
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-init
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.0
        ports:
        - containerPort: 80
      initContainers:
      - name: delay
        image: busybox
        command: [ 'sleep', '30' ]